# Generated by Django 4.2.1 on 2023-05-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simsapp.student')),
            ],
        ),
    ]
