# Generated by Django 4.2.1 on 2023-06-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('lecture', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(blank=True, max_length=100, null=True)),
                ('modulecode', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simsapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_student', models.BooleanField(default=False, verbose_name='Is student')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('saini', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.ManyToManyField(blank=True, null=True, to='simsapp.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simsapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='SignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simsapp.lecture')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_statuses_given', to='simsapp.student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_statuses_received', to='simsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='LectureUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField(blank=True, null=True)),
                ('test2', models.IntegerField(blank=True, null=True)),
                ('individual1', models.IntegerField(blank=True, null=True)),
                ('individual2', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('presentation', models.IntegerField(blank=True, null=True)),
                ('marks', models.IntegerField()),
                ('signed', models.BooleanField(blank=True, default=False, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simsapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simsapp.student'),
        ),
    ]
