# Generated by Django 4.2.1 on 2023-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0003_lectureue'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
