# Generated by Django 4.2.1 on 2023-05-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0004_student_signstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='signstatus',
        ),
        migrations.CreateModel(
            name='SignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simsapp.lecture')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simsapp.signature')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simsapp.student')),
            ],
        ),
    ]
