# Generated by Django 4.2.1 on 2023-05-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0005_remove_student_signstatus_signstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureue',
            name='signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
