# Generated by Django 4.2.1 on 2023-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0006_lectureue_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureue',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureue',
            name='individual1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureue',
            name='individual2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureue',
            name='presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureue',
            name='test1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureue',
            name='test2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
