# Generated by Django 4.2.1 on 2023-05-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0007_lectureue_group_lectureue_individual1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='saini',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signstatus',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_statuses_given', to='simsapp.student'),
        ),
        migrations.AlterField(
            model_name='signstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_statuses_received', to='simsapp.student'),
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
