# Generated by Django 4.2.1 on 2023-05-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0009_course_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureue',
            name='lecture',
        ),
    ]
