# Generated by Django 4.2.1 on 2023-05-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0010_remove_lectureue_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureue',
            name='student',
        ),
    ]
