# Generated by Django 4.2.1 on 2023-05-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0011_remove_lectureue_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureue',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simsapp.student'),
        ),
    ]
