# Generated by Django 4.2.1 on 2023-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0012_lectureue_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='saini',
        ),
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
