# Generated by Django 2.2 on 2023-05-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simsapp', '0015_module_student_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simsapp.Course'),
        ),
    ]
